### ISSUE TITLE
Element Identifiers

### ISSUE THREAD

**Issue by thombruce** [hugomodo/hugomodo#10]
Done very well so far to avoid polluting the HTML with classes, but that time is ending.

With the development of a Bootstrap theme, we need to introduce wrapper divs that serve no semantic purpose. These are required to utilise some of Bootstrap's layout features (most clearly rows and columns).

We _could_ incorporate the divs without identifiers, but I would prefer to provide a description of any particular divs purpose via an `id` or `class`. Probably `id`, given that classes are arbitrary and reusable.

## Accessibility

So I had a hunch that `id` might have some accessibility use, and this made me nervous to pursue that... and it's true, `id` is useful for accessibility. See: https://www.deque.com/blog/unique-id-attributes-matter/

But we're safe. Take the screenreader example from that page. A form field with an `aria-describedby` referencing an ID will read the contents of the element with that `id`. The `id` itself is not read aloud.

## Best Practise

Use `id` to add a descriptive label to unique elements on a page.

## Considerations

* Be descriptive
* Ensure IDs are two words or greater separated by a hyphen (how did I not know this? https://stackoverflow.com/questions/1696864/naming-class-and-id-html-attributes-dashes-vs-underlines)

## Related

This should lead to laying the foundations for #1 Accessibility Overhaul

## Todo

- [x] Use `id` to add a descriptive label to unique elements on a page.
- [x] Ensure IDs are two words or greater separated by a hyphen.
- [x] Add "wrapper" elements to main layout components.
- [x] Ensure wrapper change is non-breaking in themes:
  - [x] [Best Motherfucking Website](https://github.com/hugomodo/hugomodo-best-motherfucking-website)
  - [x] [Milligram](https://github.com/hugomodo/hugomodo-milligram)
  - [x] [Picnic](https://github.com/hugomodo/hugomodo-picnic)

**Comment by thombruce** [comment]
## Consider Using Classes Instead

### Hugo's Table of Contents and Content Headers

Hugo uses IDs to jump to headers in an article with a table of contents. These IDs are composed of the lowercase, hyphenated header content, e.g. `this-is-a-title`. If multiple headers share the same content, a number is appended, e.g. `this-is-a-title-2`.

### Conflict

Consider that a title such as **Site Title** might be used by an author, for example on a blog about HTML markup. This would produce the id `site-title`. I suspect this would create a conflict of IDs then, if I too should have used that ID in my markup.

### Two Solutions

#### Prepend or Append

This will not ensure uniqueness, but reduces the likelihood of conflict. You could consider appending or prepending a layout ID with `layout-` or `hugomodo-` or `hugomodo-layout-`.

Perhaps even better, consider some combination of the hyphen (_essential_) with underscores or camel case.

- `hugomodoLayout-article-wrapper`

Although I think I'd prefer to not mention HugoModo at all in the ID, for reusability of the concept in future projects containing markup. Aim for reusability, convention and best practise, right?

- `layout-articleWrapper`

That's good, but I'd prefer the prepend to be two words in case the main identifier is best not being.

- `siteLayout-article`

**That's excellent!** The hyphen ensures non-interference with JavaScript, and the capital letter ensures absolute non-interference with Hugo auto-generated IDs.

#### Use Classes

Classes have no need to be unique, which means styles could be broadly applied based on classes.

Consider:

```html
<article>
  <div>
    <article></article>
    <article></article>
  </div>
</article>
```

The above is not too distant from current HugoModo markup. Every page essentially has a main `article` but this _may_ contain additional `article`s.

I could apply an ID, `siteLayout-main-article`, to the top level article, and I could apply numbered IDs to child articles, `siteLayout-article-5` (or preferably some reference to its title, hashed or otherwise). However, these would not be useful for styling.

Of course, they can be targeted by virtue of being the `article` element contained within another `article` element. Hence, CSS _can_ infer they are "child articles"...

Sooooo...

## Lingering Questions

- Is the capability to add/remove these identifiers via JavaScript of use? If so, use **classes**
- Is reuse of identifiers useful at this stage for more than just styling reasons? If so, use **classes**
- Are these identifiers unique and is jumping to them of use? If so, use **IDs**
- Can non-unique elements be appropriately inferred in the CSS? If so, use **IDs**
- Are non-unique elements described well enough by their element name? If not, use **classes**

### I think we should use classes

And the use of classes would mean no dependency on hyphenation, but still the risk of conflict with frameworks. Arguably greater conflict... For example, `siteLayout-article` is totally something that could be used by a framework (though none I've so far seen does).

#### CSS Resets?

At this point then, we've actually come full circle.

Since hyphens are no longer of import, and uniqueness is less of a threat, we could just use `article` as the identifier and handle framework conflicts with reset rules.

It's cleaner. More to the point... Still... Not running head first into conflict has _got to be_ the smarter choice here.

## Decision

**Use classes!**

**Use unique identifiers, e.g.** `siteLayout-article` or `hugomodo-article` or `article-component`

Perhaps some combination of the first and last: `layout-article-component`... which is indicative of this being a layout component, specifically of the article type. Maybe... `article-layout-component`

# article-layout-component

That's the one! Consider this:

A component may also have a wrapper. Hence... `-layout-component` is the more searchable, should changes ever be needed.

- `articles-layout-container`
- `articles-layout-wrapper`
- `article-layout-component`

Something like that.

**Comment by thombruce** [comment]
Most browsers will disregard case, treating classes as case insensitive. That's no reason we can't use them ourselves...

- `layoutComponent-article`

But it probably remains best avoided... Could use underscores:

- `layout_component-article`

Perfectly valid.

**If using IDs**, modern browsers treat IDs as case sensitive:

```
layoutComponent-article != layoutcomponent-article
```

...which means our two word prefix can look "pretty" in camelCase.

I'm not saying let's revert to using IDs, but...

## If Classes

```
layout_component-article
```

## If IDs

```
layoutComponent-article
```

## That said...

snake_case is probably better either way, right? `_` is absolutely seen as an additional character, ensuring uniqueness.

Best to just start this now and see how we feel - a change after the fact will be easy enough so long as prefix names are used consistently.

## TODO

- [ ] Document the ultimate decision here.

**Comment by thombruce** [comment]
- [ ] `hugomodo_component-article`
- [ ] `hugo_component-article`
- [ ] `site_component-article`
- [ ] `hugomodo_layout-article`
- [ ] `hugo_layout-article`
- [ ] `site_layout-article`
- [ ] `tb89-article` (Why not, right? It's unique, unlikely to be duplicated, signed with my initials and YoB)

# Use Classes

Mainly for browser "jump to anchor" behaviour. You don't want this in a URL: `#hugomodo_component-article`. Let the user override with their own classes, not using these for style selection?

# Use IDs

Mainly for assistive technologies and the future use of `aria-` attributes.

**Because this is essential, it supersedes the previous idea!** _An end user can always add "pretty anchors" by dropping empty divs into overwritten layout components._

**By using IDs, we prepare for a future consideration.**

_By using IDs, we support easier behavioural modification of single components using JavaScript._

I think we're back on IDs. Oops! 😅

**Comment by thombruce** [comment]
Using IDs, for non-unique components use starts with and ends with CSS selectors. https://stackoverflow.com/a/42497426/2225649

For example:

```
<article id="layout_component-article-s0M3h4Sh"></article>
```

```
article[id^='layout_component-article'] {
  // some style rule
}
```

**Comment by thombruce** [comment]
## Consider Breadcrumb Nav

### An Issue of Reusability vs Accessibility

At present, I only use one breadcrumb nav on a page... but nothing's to stop somebody including the partial twice.

If they do so, and I've used IDs, then the markup becomes invalid.

If I use classes, the ID cannot be used for aria attribute accessibility... but `aria-label` can be used instead.

**No way to numerate.** _(No sane way, anyway.)_

## Here's a thought...

We can continue to use ID where the item can or should only be used once.

We can use class where that is not the case.

To differentiate:

- `hugoModule-siteTitle`
- `hugoComponent-breadcrumbNav`

...with the intent that modules be usable only once, and components reusable countless times.

**Comment by thombruce** [comment]
## To be continued...

Closing with 1c01c0fe38f3200a3d1e8a44ae4450f9f753c7fb

I expect that's not complete... although perhaps the inverse is true and I've gone further than I need to.

Today I've merely added something that I know will be needed - a top-level wrapper (see commit).

I want to investigate this further as I develop more advanced theme functionality. Of particular interest are grid based themes (e.g. Bootstrap, Foundation). They should reveal more. But as to exactly what's needed... that shall be a consideration of _how do we achieve this new layout?_ For instance, a two-column sidebar layout...

We want modularity and manoeuvrability of markup.
